# Generated by Django 2.0.5 on 2019-01-06 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Check_xovis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(verbose_name='time to check')),
                ('result', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Xovis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=15)),
                ('serial', models.CharField(max_length=23)),
                ('name', models.CharField(max_length=150)),
                ('used', models.BooleanField(default=True)),
                ('group', models.CharField(max_length=50)),
                ('priority', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='check_xovis',
            name='ip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='check_xovis.Xovis'),
        ),
    ]
